version: 2.1

orbs:
  python: circleci/python@1.4.0

jobs:
  setup:
    description: Set Up Venv and Warm Cache
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Python Version
          command: python --version
      - run:
          name: Poetry Version
          command: poetry --version

  format:
    description: Check Code Format
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Run black
          command: poetry run black --check --diff .

  lint:
    description: Check Lints
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Run flake8
          command: poetry run flake8

  typing:
    description: Check Static Typing
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Run mypy
          command: poetry run mypy easyrepr

  unit-test:
    description: Verify that Unit Tests Pass
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Run pytest
          command: poetry run pytest --junitxml=test-results/junit.xml --verbose
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results

  build:
    description: Build the Distribution
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Build distribution
          command: poetry build
      - store_artifacts:
          path: dist
      - persist_to_workspace:
          root: .
          paths: dist/*

  publish-pypi:
    description: Publish to PyPI
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - attach_workspace:
          at: .
      - run:
          name: Publish Distribution to PyPI
          command: poetry publish

# Private map with some common job filter definitions.
.filters:
  all-branches-and-tags: &all-branches-and-tags
    branches:
      only: /.*/
    tags:
      only: /.*/

  only-version-tags: &only-version-tags
    branches:
      ignore: /.*/
    tags:
      only: /^v\d+\.\d+\.\d+/

workflows:
  version: 2
  ci:
    jobs:
      - setup:
          filters:
            <<: *all-branches-and-tags
      - format:
          requires:
            - setup
          filters:
            <<: *all-branches-and-tags
      - lint:
          requires:
            - setup
          filters:
            <<: *all-branches-and-tags
      - typing:
          requires:
            - setup
          filters:
            <<: *all-branches-and-tags
      - unit-test:
          requires:
            - setup
          filters:
            <<: *all-branches-and-tags
      - build:
          requires:
            - format
            - lint
            - typing
            - unit-test
          filters:
            <<: *all-branches-and-tags
      - publish-pypi:
          context: easyrepr/publish-pypi
          requires:
            - build
          filters:
            <<: *only-version-tags
